name: Deploy website

on:
  workflow_dispatch:
    inputs:
      library:
        description: "Library name"
        required: true
        default: "std"
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qilletni/qilletni:snapshot
    permissions:
      contents: read
      deployments: write

    name: Deploy to Cloudflare Pages
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download latest of library
        run: curl https://qpm.qilletni.dev/packages/qilletni/${{ github.event.inputs.library }}/latest -o /tmp/library.qll

      - name: Get library version
        run: |
          VERSION=$(curl -s https://qpm.qilletni.dev/packages/qilletni/${{ github.event.inputs.library }}/latest/metadata | jq -r '.version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build docs
        run: qilletni doc -c cache/ -o serve/ /tmp/library.qll

      - name: Commit and push changes
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add serve/ cache/
          git commit -m "Update documentation for ${{ github.event.inputs.library }} ${{ env.VERSION }}" || echo "No changes to commit"
          git push

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy serve --project-name=${{ secrets.QILLETNI_DOCS_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
